services:
  database:
    image: bitnami/postgresql:16.1.0
    environment:
      POSTGRESQL_USERNAME: library
      POSTGRES_PASSWORD: library
      POSTGRESQL_DATABASE: library
    ports:
      - "5432:5432"
    volumes:
      - db-data:/bitnami/postgresql:rw
  cache:
    image: redis/redis-stack
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  db-data:
